sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: bronya-demo
  redis:
    host: 192.168.92.132
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid:
    secret:
